### ISSUE TITLE
Final v4.0.0 release TODO

### ISSUE THREAD

**Issue by jockri** [Kunstmaan/KunstmaanBundlesCMS#1209]
- [x] Support Symfony 3
- [x] Remove old migrate commands that were used to migrate to previous versions
- [x] Remove LiveReloadBundle and LanguageChooserBundle
- [x] Remove deprecated code
- [x] Fix travis
- [x] Change documentation: app/console -> bin/console etc
