### ISSUE TITLE
Roadmap to sf4

### ISSUE THREAD

**Issue by deZinc** [Kunstmaan/KunstmaanBundlesCMS#1993]
Fix all these deprecations (and search for more):

- [x] Security.acl.object_identity_retrieval_strategy is a symfony service, should be public in  src/Kunstmaan/NodeBundle/Controller/NodeAdminController.php:1214. Possible solution is to create our own acl handler service
- [x] The "fos_user.user_manager" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. Possible solution is creating our own user manager service. For now, based on the fos user version, but should enable us to easily replace fos user in the feature
- [x] Console.exception event is deprecated, replace our listener? 
- [x] Refactor "\Kunstmaan\NodeSearchBundle\Configuration\NodePagesConfiguration" to not use the container? Or make services public?
- [x] IN PR: The "kunstmaan_admin.adminroute.helper" service is private
- [x] The "translation.loader.php" service is private (etc….). Solution: refactor our translator, remove the container injection. Try to find different way to extend the translator.

Structural:

- [x] Must fix: Refactor generate commands to support bundleless setup and sf4 structure
- [ ] To decide: Replace parameters.yml with .env???? To do or not to do?
- [ ] Nice to have: Reduce / remove getting services from the container instead of injecting them

Flex:

- [ ] Analyze if and how we can go “micro” ourselves, separating the bundles in independent packages as far as  possible and create recipes for our “bundles”
- [ ] Custom installer instead of using the flex recipes? https://medium.com/@endroid/auto-package-configuration-for-symfony-e14780e29d81

**Comment by acrobat** [comment]
Closing this issue as version 5.3 is compatible with symfony 4.
