### ISSUE TITLE
Prepare code to remove deprecated symfony/templating component

### ISSUE THREAD

**Issue by acrobat** [Kunstmaan/KunstmaanBundlesCMS#2555]
Prepare our code to remove the deprecated symfony/templating component.

TODO:

- [x] Replace the old twig path notation by the twig namespaced notation. `KunstmaanAdminBundle:Example:Template.html.twig` -> `@KunstmaanAdmin/Example/Template.html.twig`. See #2553
- [x] Deprecate service injection of `@templating` and replace by `@twig`
   - [x] `Kunstmaan\AdminListBundle\Service\ExportService`. See #2556
   - [x] `Kunstmaan\FormBundle\Helper\FormMailer`. See #2559
   - [x] `Kunstmaan\ConfigBundle\Controller\ConfigController`. See #2559
- [x] Set `fos_user.service.mailer` config to `fos_user.mailer.twig_swift`. See #2554

**Comment by acrobat** [comment]
All todo's have fixed (see linked PR's)
